name: Metrics
on:
  #push:
  #issues:
    #types: [opened, edited, closed]
    workflow_dispatch:

permissions:
  contents: write
  
jobs:
  count_commits_and_issues:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: gh-pages  

      - name: Get metrics
        id: get_metrics
        run: |
          cd docs
          cd scripts
          python metrics.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
      - name: Committing results
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git add docs/metrics.json
          git commit -m "Updated metrics.json" || exit 0
          git push