name: Tests
on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 

      - name: Tests
        id: tests
        run: |
          cd docs
          cd scripts
          python -B -m unittest discover -s tests -p "Test*.py"

